services:  # services 아래 서비스들을 명시
  nodejs:  # nodejs라는 이름의 서비스를 정의
    build:  # 빌드 옵션
      dockerfile: node.Dockerfile  # node.Dockerfile 을 사용하여 build.
    ports:
      - 8200:8000  # <로컬에서 열 포트이름>:<docker container에서 열어 놓은 port 이름>
    env_file: ../.env  # .env 파일 위치
    restart: unless-stopped
  
  python:
    build:
      dockerfile: python.Dockerfile
    ports:
      - 5200:5000
    env_file: ../.env
    restart: unless-stopped